# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.7


### Exercícios Sobre Módulos Python Para Análise de Dados

### ****** ATENÇÃO ******
### Alguns dos exercícios podem requerer pesquisa adicional na documentação dos pacotes. Pesquise!

### Exercício 1

In [2]:
# Crie um array NumPy com 1000000 e uma lista com 1000000.
# Multiplique cada elemento do array e da lista por 2 e calcule o tempo de execução com cada um dos objetos (use %time).
# Qual objeto oferece melhor performance, array NumPy ou lista?
import numpy as np
import random as rm
import sqlite3 as sql

# Alocando memória
array_numpy = np.random.randn(1000000)
lista = [rm.random() for _ in range(0, 1000000)]

# Multiplicando por 2 e calculando tempo
%time array_numpy = array_numpy * 2
%time for i in range(0, len(lista)): lista[i] *= 2

Wall time: 4 ms
Wall time: 103 ms


### Exercício 2

In [3]:
# Exercício 2
# Crie um array de 10 elementos
# Altere o valores de todos os elementos dos índices 5 a 8 para 0

# Criando vetor de 1 a 10
arr = np.arange(10)

# Alterando 5 a 8 para 0
arr[5:8] = 0
    
arr

array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9])

### Exercício 3

In [4]:
# Crie um array de 3 dimensões e imprima a dimensão 1 

# Criando array de 27 elementos
arr = np.arange(3**3)

# Rearranjando ele para ser um array 3x3x3
arr = np.reshape(arr, (3,3,3))

# Printando dimensão 1
arr[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Exercício 4

In [5]:
# Crie um array de duas dimensões (matriz).
# Imprima os elementos da terceira linha da matriz
# Imprima todos os elementos da primeira e segunda linhas e segunda e terceira colunas

# Criando array de 1 a 9 e rearranjando para matriz 3x3
arr = np.reshape(np.arange(3**2), (3,3))

# Imprimindo terceira linha
print(arr[2], '\n')

# Imprimindo intersecção
print(arr[0:2, 1:3])

[6 7 8] 

[[1 2]
 [4 5]]


### Exercício 5

In [6]:
# Calcule a transposta da matriz abaixo
arr = np.arange(15).reshape((3, 5))

arr.transpose()

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Exercício 6

In [7]:
# Considere os 3 arrays abaixo
# Retorne o valor do array xarr se o valor for True no array cond. Caso contrário, retorne o valor do array yarr.
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

# Criando uma lista com valores de xarr_i se cond_i ou então yarr_i
list(map(lambda x,y,c: x if c else y, xarr, yarr, cond))

[1.1, 2.2, 1.3, 1.4, 2.5]

### Exercício 7

In [8]:
# Crie um array A com 10 elementos e salve o array em disco com a extensão npy
# Depois carregue o array do disco no array B

# Criando vetor de 0 a 9
A = np.arange(0, 10)

# Gravando no disco
np.save('exercicio_7.npy', A)

# Carregando em B
B = np.load('exercicio_7.npy')
B

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Exercício 8

In [9]:
# Considerando a série abaixo, imprima os valores únicos na série
import pandas as pd
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c', 'a', 'b'])

obj.unique()

array(['c', 'a', 'd', 'b'], dtype=object)

### Exercício 9

In [10]:
# Considerando o trecho de código que conecta em uma url na internet, imprima o dataframe conforme abaixo.
import requests
url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
resp = requests.get(url)

pd.read_json(resp.content)[['number', 'title', 'labels', 'state']]

number                                              title  \
0    44030                      BUG: .fillna({}) doesn't work   
1    44029             ENH/CI: Add Cache for Azure pipelines    
2    44028  Temporarily add back Index._get_attributes_dic...   
3    44027         Consider cibuildwheel for building wheels?   
4    44026  BUG: Using pd.to_datetime function in groupby....   
5    44025  BUG: DatetimeIndex.intersection with non-ancho...   
6    44024            ENH: Why neg rolling is too much hard?!   
7    44023                 Bug multiple css selectors GH44011   
8    44022  ENH: Ability to coerce floats when reading csv...   
9    44021  BUG: pandas.read_fwf doesn't correctly works w...   
10   44020                             DOC: DatetimeArray.std   
11   44019                              BUG: RangeIndex.union   
12   44018                    DOC: Upload cheatsheets to site   
13   44017                                               ENH:   
14   44015             TST: More type checking during .(i)loc   
15   44014  BUG: Compare returns wrong results for nullabl...   
16   44011  BUG: Multiple CSS selectors using set_table_st...   
17   44009  BUG: Inconsistency between behavior of cumsum ...   
18   44008  BUG: sum() and mean() return wrong values when...   
19   44007  DOC: Added DataFrame in Parameters & Return de...   
20   44006             CLN: pragma no cover, post-array_ufunc   
21   44005           TST: Adding test to test_numeric, #37348   
22   44003  [BUG] Fix DataFrameGroupBy.boxplot with subplo...   
23   44002  ENH: Support observed keyword argument in Cate...   
24   44001  BUG: Inconsistent behaviour for DataFrame.valu...   
25   44000  BUG: Index.union with both bools and ints, dup...   
26   43999  ENH: Default to `observed=True` in `DataFrame....   
27   43998  BUG: Fix for rolling with uneven nanosecond wi...   
28   43997  BUG: rolling with uneven nanosecond window hav...   
29   43996  BUG: v1.3.0 Introduces Unexpected Retyping of ...   

                                               labels state  
0   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
1                                                  []  open  
2   [{'id': 76865106, 'node_id': 'MDU6TGFiZWw3Njg2...  open  
3                                                  []  open  
4   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
5   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
6   [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
7                                                  []  open  
8                                                  []  open  
9   [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
10  [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OT...  open  
11                                                 []  open  
12                                                 []  open  
13  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
14                                                 []  open  
15  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
16  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
17  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
18  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
19                                                 []  open  
20                                                 []  open  
21  [{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2OD...  open  
22                                                 []  open  
23  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
24  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
25  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
26  [{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...  open  
27  [{'id': 1045950827, 'node_id': 'MDU6TGFiZWwxMD...  open  
28  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open  
29  [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...  open

### Exercício 10

In [22]:
# Crie um banco de dados no SQLite, crie uma tabela, insira registros, 
# consulte a tabela e retorne os dados em dataframe do Pandas
connection = sql.connect('exercicio_10.db')
cursor = connection.cursor()

# Criando a tabela test
cursor.execute('''CREATE TABLE IF NOT EXISTS test (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    nome TEXT NOT NULL
                 )''')
connection.commit()
display(pd.read_sql_query('SELECT * FROM sqlite_master', connection))

# Inserindo dados
def inserir_registro(nome: str):
    """Insere um registro dentro do banco sqlite
    Args:
        nome (str)
    """
    cursor.execute(f'''INSERT INTO test (nome) VALUES ('{nome}')''')

inserir_registro('Matteuw')
inserir_registro('Nickoff')
connection.commit()

# Mostrando os dados
display(pd.read_sql_query('SELECT * FROM test', connection))

# Fechando conexão
connection.close()

type  name tbl_name  rootpage  \
0  table  test     test         2   

                                                 sql  
0  CREATE TABLE test (\n                    id IN...

id     nome
0   1  Matteuw
1   2  Nickoff
2   3  Matteuw
3   4  Nickoff

# Fim


### Obrigado

### Visite o Blog da Data Science Academy - <a href="http://blog.dsacademy.com.br">Blog DSA</a>
